openapi: "3.0.3"
info:
  title: Keiz! Admin API
  version: 1.0.0
servers:
  - url: https://api.admin.ag-keiz.com
    description: Production Server
  - url: https://stg.api.admin.ag-keiz.com
    description: Staging Server
  - url: https://dev.api.admin.ag-keiz.com
    description: Development Server
  - url: http://localhost:8080
    description: Local Server
paths:
  /cars:
    $ref: "./paths/car.yaml#/cars"
  /cars/{carId}:
    $ref: "./paths/car.yaml#/cars_{carId}"
  /cars/{carId}/images:
    $ref: "./paths/car.yaml#/cars_{carId}_images"
  /cars/{carId}/images/{imageId}:
    $ref: "./paths/car.yaml#/cars_{carId}_images_{imageId}"
  /cars/{carId}/prices:
    $ref: "./paths/car.yaml#/cars_{carId}_prices"
  /cars/{carId}/prices/{priceId}:
    $ref: "./paths/car.yaml#/cars_{carId}_prices_{priceId}"
  /attributes:
    $ref: "./paths/attribute.yaml#/attributes"
  /attributes/{attributeId}:
    $ref: "./paths/attribute.yaml#/attributes_{attributeId}"
  /attributes/{attributeId}/choices:
    $ref: "./paths/attribute.yaml#/attributes_{attributeId}_choices"
  /attributes/{attributeId}/choices/{choiceId}:
    $ref: "./paths/attribute.yaml#/attributes_{attributeId}_choices_{choiceId}"
components:
  securitySchemes:
    AuthBearer:
      $ref: "./components/securitySchemes/basic.yaml#/AuthBearer"
