openapi: "3.0.3"
info:
  title: Keiz! Web API
  version: 1.0.0
  license:
    name: All Rights Reserved
    url: https://ag-keiz.com
  contact:
    name: Keiz!
    url: https://ag-keiz.com
    email: hq@ag-keiz.com
servers:
  - url: https://api.ag-keiz.com
    description: Production Server
  - url: https://stg.api.ag-keiz.com
    description: Staging Server
  - url: https://dev.api.ag-keiz.com
    description: Development Server
paths:
  /cars:
    $ref: "./paths/car.yaml#/cars"
  /cars/{carId}:
    $ref: "./paths/car.yaml#/cars_{carId}"
